FROM debian:bullseye-slim

COPY src /app/src

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apache2 \
        bash \
        curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
USER root
EXPOSE 80

ENTRYPOINT ["httpd", "-D", "FOREGROUND"]

